ProjectMVC/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectMVC.Models;
using System.IO;
using log4net;

namespace ProjectMVC.Controllers
{
    public class StudentController : Controller
    {
        private SchoolContext db = new SchoolContext();

        //creating a instance of log
        ILog logger = LogManager.GetLogger(typeof(StudentController));

        public ActionResult Search(String SearchBox)
        {
            //select * from db.Student s where s.lastName = SearchBox
            //linq to SQL statements
            var Students = (from s in db.student
                           where s.LastName.Contains(SearchBox) || s.FirstName.Contains(SearchBox)
                           select s).ToList();
            return View("Index",Students); //denotes call the index page based on the student object.
        }



        // GET: Student
        public ActionResult Index()
        {
            logger.Info("enter student index");
            //linq to entities statement
            return View(db.student.ToList());
        }

        // GET: Student/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                logger.Error("no id");
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.student.Find(id);
            if (student == null)
            {
                logger.Error("no id");
                return HttpNotFound();
            }
            logger.Debug("return student");
            return View(student);
        }

        // GET: Student/Create. Whenever we click on a link it will call the get method
        //No values passed it is just to get the form.
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create. Whenever we click on button it will call the HttpPost annotation.
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudentId,firstName,lastName,EnrollmentDate")] Student student, HttpPostedFileBase ImageFile)//Bind(Include= ) optional
        {
            if (ModelState.IsValid) //check if all the values are valid.
            {
                if(ImageFile != null) //Whatever image is uploaded is not null
                {
                    //
                    string pic = System.IO.Path.GetFileName(ImageFile.FileName); //first get the file name
                    string path = System.IO.Path.Combine(Server.MapPath("~/images/profiles"), pic); //Create the path

                    //file is uploaded
                    ImageFile.SaveAs(path);

                    student.ImagePath = pic; //which pic is associated with which student

                    //Save the image path to the database or send image directly to the database.
                    //in case if we want to store byte[] ie for DB.
                    using(MemoryStream ms = new MemoryStream())
                    {
                        ImageFile.InputStream.CopyTo(ms);
                        student.Picture = ms.GetBuffer();
                    }
                }

                db.student.Add(student);
                db.SaveChanges();
                return RedirectToAction("Index"); //redirect to the index action method in student controller which in turn fetch all the student values and return a view.
            }

            return View(student);
        }

        // GET: Student/Edit/5
        //if Edit needs more parameter it can be passed like public ActionResult Edit(int? id, String abc)
        public ActionResult Edit(int? id) 
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.student.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudentId,firstName,lastName,EnrollmentDate")] Student student)
        {
            if (ModelState.IsValid)
            {
                //This line tells that the student object is not a new object. Existing object has been modified
                db.Entry(student).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        // GET: Student/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Student student = db.student.Find(id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        // POST: Student/Delete/5
        [HttpPost, ActionName("Delete")] 
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) //no two same methods receive one Id.
        {
            Student student = db.student.Find(id);
            db.student.Remove(student);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //to display a image
        public ActionResult GetImage(int id)
        {
            //find the particular picture for a student by id and returns a particular image
            byte[] imagedata = db.student.Find(id).Picture;
            return File(imagedata, "image/jpeg"); //depends on the type of image
        }
    }
}

ProjectMVC/Controllers/XyzController.cs
using ProjectMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectMVC.Controllers
{
    public class XyzController : Controller
    {
        private SchoolContext db = new SchoolContext();
        // GET: Xyz
        public ActionResult Abc()
        {
            //This statement means that fetch everything from the student class which in turn connected to the table and 
            //convert it to a list and put it in var students.
            var students = db.student.ToList();
            return View(students);
            
            //Course math = new Course();
            //math.CourseName = "Maths";
            //math.TotalCredits = 4;

            //Student alex = new Student();
            //alex.firstName = "Alex";
            //alex.lastName = "Rod";

            //Student lynda = new Student();
            //lynda.firstName = "Lynda";
            //lynda.lastName = "Berry";

            //Student jhon = new Student();
            //jhon.firstName = "jhon";
            //jhon.lastName = "Doe";

            //List<Student> students = new List<Student>();
            //students.Add(alex);
            //students.Add(lynda);
            //students.Add(jhon);

            //CourseStudents obj = new CourseStudents();
            //obj.course = math;
            //obj.students = students;

            //Language Integrated Query

            //return View(obj);


        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjectMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                                        @*DisplayName, ActionMethodName, ControllerName*@
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("xyz-abc", "Abc", "Xyz")</li>*@
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("Course", "Index", "Course")</li>
                    <li>@Html.ActionLink("Enrollment", "Index", "Enrollment")</li>
                    <li>@Html.ActionLink("Instructor", "Index", "Instructor")</li>
                    <li>@Html.ActionLink("Department", "Index", "Department")</li>
                    <li>@Html.ActionLink("Teacher-Assigned", "Index", "CourseInstructor")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Anwar Project</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProjectMVC/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
        <title>Bootply.com - Collapsing sidebar drawer menu</title>
        <meta name="generator" content="Bootply" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet">
        
        <!--[if lt IE 9]>
          <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]--

        <!-- CSS code from Bootply.com editor -->
        
        <style type="text/css">
            body {
  padding-top: 51px;  
}
.text-center {
  padding-top: 20px;
}
.col-xs-12 {
  background-color: #fff;
}
#sidebar {
  height: 100%;
  padding-right: 0;
  padding-top: 20px;
}
#sidebar .nav {
  width: 95%;
}
#sidebar li {
  border:0 #f2f2f2 solid;
  border-bottom-width:1px;
}

/* collapsed sidebar styles */
#media screen and (max-width: 767px) {
  .row-offcanvas {
    position: relative;
    -webkit-transition: all 0.25s ease-out;
    -moz-transition: all 0.25s ease-out;
    transition: all 0.25s ease-out;
  }
  .row-offcanvas-right
  .sidebar-offcanvas {
    right: -41.6%;
  }

  .row-offcanvas-left
  .sidebar-offcanvas {
    left: -41.6%;
  }
  .row-offcanvas-right.active {
    right: 41.6%;
  }
  .row-offcanvas-left.active {
    left: 41.6%;
  }
  .sidebar-offcanvas {
    position: absolute;
    top: 0;
    width: 41.6%;
  }
  #sidebar {
    background-color:#3b3b3b;
    padding-top:0;
  }
  #sidebar .nav>li {
    color: #ddd;
    background: linear-gradient(#3E3E3E, #383838);
    border-top: 1px solid #484848;
    border-bottom: 1px solid #2E2E2E;
  }
  #sidebar .nav>li:first-child {
    border-top:0;
  }
  #sidebar .nav>li>a {
    color: #ddd;
  }
  #sidebar .nav>li>a>img {
    max-width: 14px;
  }
  #sidebar .nav>li>a:hover, #sidebar .nav>li>a:focus {
    text-decoration: none;
    background: linear-gradient(#373737, #323232);
    color: #fff;  
  }
  #sidebar .nav .caret {
    border-top-color: #fff;
    border-bottom-color: #fff;
  }
  #sidebar .nav a:hover .caret{
    border-top-color: #fff;
    border-bottom-color: #fff;
  }
}


        </style>
    </head>
    
    <!-- HTML code from Bootply.com editor -->
    
    <body  >
        
        <div class="page-container">
  
	<!-- top navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
       <div class="container">
    	<div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="offcanvas" data-target=".sidebar-nav">
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
           <a class="navbar-brand" href="#">Project Name</a>
    	</div>
       </div>
    </div>
      
    <div class="container">
      <div class="row row-offcanvas row-offcanvas-left">
        
        <!-- sidebar -->
        <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
			   <li>@Html.ActionLink("Students", "Index", "Student")</li>
               <li>@Html.ActionLink("Course", "Index", "Course")</li>
               <li>@Html.ActionLink("Enrollment", "Index", "Enrollment")</li>
              <li><a href="#">Link 1</a></li>
              <li><a href="#">Link 2</a></li>
              <li><a href="#">Link 3</a></li>              
            </ul>
        </div>
  	
        <!-- main area -->
        <div class="col-xs-12 col-sm-9">
          <h1>Shrink Width to Collapse Sidebar</h1>
         @RenderBody()
          
        </div><!-- /.col-xs-12 main -->
    </div><!--/.row-->
  </div><!--/.container-->
</div><!--/.page-container-->
        
        <script type='text/javascript' src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>


        <script type='text/javascript' src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>





        
        <!-- JavaScript jQuery code from Bootply.com editor -->
        
        <script type='text/javascript'>
        
            $(document).ready(function() {
  $('[data-toggle=offcanvas]').click(function() {
    $('.row-offcanvas').toggleClass('active');
  });
});
        
        </script>
        
    </body>
</html>

ProjectMVC/Views/Shared/_LayoutDetails.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                                        @*DisplayName, ActionMethodName, ControllerName*@
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("xyz-abc", "Abc", "Xyz")</li>*@
                    <li>@Html.ActionLink("Students", "Index", "Student")</li>
                    <li>@Html.ActionLink("Course", "Index", "Course")</li>
                    <li>@Html.ActionLink("Enrollment", "Index", "Enrollment")</li>
                    <li>@Html.ActionLink("Instructor", "Index", "Instructor")</li>
                    <li>@Html.ActionLink("Department", "Index", "Department")</li>
                    <li>@Html.ActionLink("Teacher-Assigned", "Index", "CourseInstructor")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @{Html.RenderAction("GetDepartments", "Department");}
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>